name: MGFX.Tabs
author: seanmonstar
category: Interface
tags: [tabs]
docs: http://github.com/seanmonstar/MGFX.Tabs/blob/master/Docs/mgfxtabs.md
demo: http://seanmonstar.github.com/MGFX.Tabs/
current: 1.3.0